### ISSUE TITLE
0.4.0-1.20.1 Small hexerei plants are destroyed when harvested. 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [JoeFoxe/Hexerei-0.2.1-1.18#87]
Belladonna and mandrake are no longer harvestable when punched; they used to drop the plant itself, and now are destroyed. 
Yellow dock and mugwort break normally and drop the item.

**Comment by JoeFoxe** [comment]
dangit I knew I missed something when renaming them, I and so many got it confused that the belladonna and mandrake had the id of "belladonna flower" instead of "belladonna plant" same goes for mandrake, so I had to fix all the ids and names to correspond, and I just forgot to rename the loot table file to the plant instead of flower, so thatll be fixed in the next update (real soon here)
